version: '3'
services:
  shortly:
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    expose:
        - "27017"
    ports:
      - "0.0.0.0:27017:27017"